vk:
  domen: api.vk.com
  methods:
    countries: /method/database.getCountries
    cities: /method/database.getCities
    universities: /method/database.getUniversities
  base_dir: /home/deos/Spalah_Practice/Pr_05/data